name: "Validate & Build"

on:
  workflow_call:

jobs:
  Sanity:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Modify package.json for dev branch
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            sed -i 's/"@vmohammad\/plugins"/"@vmohammad\/plugins (dev)"/g' package.json
            echo "Modified package.json name for dev branch"
          else
            echo "Not on dev branch, keeping original package.json name"
          fi

      - name: Install pnpm 📥
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Node.js 📥
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: Install dependencies 📥
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luna-artifacts
          path: ./dist
